### ISSUE TITLE
Traffic Light

### ISSUE THREAD

**Issue by hchocobar** [4GeeksAcademy/hchocobar-react-hello#37]
# ChecList

# Efecto

```css

.glow-red {
  box-shadow: 0px 0px 9px 4px red;
  animation: glow 0.8s linear infinite alternate;
}
.glow-yellow {
  box-shadow: 0px 0px 9px 4px yellow;
  animation: glow 0.8s linear infinite alternate;
}
.glow-green {
  box-shadow: 0px 0px 9px 4px green;
  animation: glow 0.8s linear infinite alternate;
}

@keyframes glow {
  to {
      box-shadow: 0px 0px 30px 20px yellowgreen;
  }
}

```

**Comment by hchocobar** [comment]
```css

/* Simple Counter Bonus*/
.big-counter {
    text-align: center;
    background: black;
}

.big-counter div {
    display: inline-block;
    font-size: 60px;
    background: #161B22;
    border-radius: 5px;
    color: white;
    padding: 10px;
    margin: 3px;
}
```
